---
layout:   post
title:    "早盘资讯"
category:  strategy
tags:     
    -  
    -   
description: 
published: false
status:    process
---

<!------------------------------------------------------------------------------------------------------->
```{r echo=FALSE, warning=FALSE, message=FALSE}
library(rvest)
library(beepr)
```
<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
url <- "http://www.zf826.com/category/zf1"
link <- url %>% 
  read_html() %>% 
  html_nodes(".post-list-title   .fl") %>% 
  html_attr("href")

article <- function(x){
  link <- x
  
  title  <- x %>% 
    read_html() %>% 
    html_nodes(".single-title") %>% 
    html_text()

  date <- x %>% 
    read_html() %>% 
    html_nodes(".single-info   span") %>% 
    html_text() %>%
    .[1]

  main <- x %>%
    read_html()  %>% 
    html_nodes("#single-con   p") %>% 
    html_text() %>% 
    paste(., collapse = '\n                                                                                              \n') %>%
    gsub("———-|———|－－－－－－|。　　|——", "\n                                                                                              \n", .) %>%
    gsub("　　", "", .) %>%
    gsub("○|＞|>", "\n\n \\- ",.,) %>%
    gsub("点评：", "\n                                                                                              \n > \\**点评：\\**", .) 

  all <- list(link, title, date, main)   ## all information: link, title, date, main
  return(all)
}

inf <- lapply(link[1:6], article)
```

<!------------------------------------------------------------------------------------------------------->

<h3>  `r inf[[1]][[2]]` </h3>
[`r inf[[1]][[3]]`](`r inf[[1]][[1]]`)

`r inf[[1]][[4]]`

<!------------------------------------------------------------------------------------------------------->

<h3>  `r inf[[2]][[2]]` </h3>
[`r inf[[2]][[3]]`](`r inf[[2]][[1]]`)

`r inf[[2]][[4]]`

<!------------------------------------------------------------------------------------------------------->

<h3>  `r inf[[3]][[2]]` </h3>
[`r inf[[3]][[3]]`](`r inf[[3]][[1]]`)

`r inf[[3]][[4]]`

<!------------------------------------------------------------------------------------------------------->

<h3>  `r inf[[4]][[2]]` </h3>
[`r inf[[4]][[3]]`](`r inf[[4]][[1]]`)

`r inf[[4]][[4]]`

<!------------------------------------------------------------------------------------------------------->

<h3>  `r inf[[5]][[2]]` </h3>
[`r inf[[5]][[3]]`](`r inf[[5]][[1]]`)

`r inf[[5]][[4]]`

<!------------------------------------------------------------------------------------------------------->

<h3>  `r inf[[6]][[2]]` </h3>
[`r inf[[6]][[3]]`](`r inf[[6]][[1]]`)

`r inf[[6]][[4]]`
<!------------------------------------------------------------------------------------------------------->
<!------------------------------------------------------------------------------------------------------->
<!------------------------------------------------------------------------------------------------------->

```{r echo=FALSE, warning=FALSE, message=FALSE}
beep()
```
