permalink: /:year/:month/:day/:title.html                     ##     /investment/
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: William Fang
  email: william.lian.fang@gmail.com
  # link:  
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/williamlfang
  # music: http://site.douban.com/linanya
  # linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 价值投资者
description: Website for Investment
url: http://williamlfang.github.com/        ## {{ site.url }}/
sub_url: /investment
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /investment/public/img/william.png                         ##         
favicon: /investment/public/img/deer3.png                         ##

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: tags

# 首页除了最新文章外显示分类
cates: 
  - Linux
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
